// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YogurtFinder.Models;

namespace YogurtFinder.Migrations
{
    [DbContext(typeof(YogurtFinderContext))]
    [Migration("20200818171509_NewData")]
    partial class NewData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("YogurtFinder.Models.Yogurt", b =>
                {
                    b.Property<int>("YogurtId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Blended");

                    b.Property<string>("Brand")
                        .IsRequired();

                    b.Property<int>("Calories");

                    b.Property<int>("Carbs");

                    b.Property<int>("Fat");

                    b.Property<string>("Flavor")
                        .IsRequired();

                    b.Property<int>("Protein");

                    b.Property<int>("Sugar");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("YogurtId");

                    b.ToTable("Yogurts");
                });
#pragma warning restore 612, 618
        }
    }
}
